import { writeFile, readFile, stat, copyFile } from "fs/promises";
import { existsSync } from "fs";
import { createHash } from "crypto";
import { extname, basename, dirname, join } from "path";
import type { Tool, ToolResult, ToolContext } from "./types";
import { formatResponse, formatError } from "./types";

// ── Types ───────────────────────────────────────────────────

interface MeshOptions {
  overwrite?: boolean;
  createDirectories?: boolean;
  materialName?: string;
  copySourceFiles?: boolean;
  outputFormat?: "obj" | "glb" | "gltf";
}

interface ColorRGB {
  r: number;
  g: number;
  b: number;
}

interface MaterialProperties {
  ambient?: ColorRGB;
  diffuse?: ColorRGB;
  specular?: ColorRGB;
  shininess?: number;
  opacity?: number;
}

interface ParsedObj {
  vertices: Float32Array;
  normals: Float32Array | null;
  texCoords: Float32Array | null;
  faces: Uint32Array;
}

interface FaceVertex {
  vi: number;
  ti: number;
  ni: number;
}

interface GltfDocument {
  asset: { version: string; generator: string };
  scene: number;
  scenes: { nodes: number[] }[];
  nodes: { mesh: number }[];
  meshes: { primitives: { attributes: Record<string, number>; indices: number; material: number }[] }[];
  materials: Record<string, unknown>[];
  textures: { source: number; sampler: number }[];
  samplers: Record<string, number>[];
  images: Record<string, unknown>[];
  accessors: Record<string, unknown>[];
  bufferViews: Record<string, unknown>[];
  buffers: Record<string, unknown>[];
  _binaryBuffer?: Buffer;
}

// ── Constants ───────────────────────────────────────────────

const MAX_FILE_SIZE = 200 * 1024 * 1024; // 200MB
const SUPPORTED_TEXTURE_FORMATS = ["png", "jpg", "jpeg", "tga", "bmp", "tiff", "webp"];
const SUPPORTED_OUTPUT_FORMATS = ["obj", "glb", "gltf"];

// ── Helpers ─────────────────────────────────────────────────

function calculateChecksum(buffer: Buffer): string {
  return createHash("sha256").update(buffer).digest("hex");
}

function getMimeType(ext: string): string {
  const mimeTypes: Record<string, string> = {
    png: "image/png",
    jpg: "image/jpeg",
    jpeg: "image/jpeg",
    gif: "image/gif",
    webp: "image/webp",
    tga: "image/x-targa",
    bmp: "image/bmp",
    tiff: "image/tiff",
  };
  return mimeTypes[ext] || "application/octet-stream";
}

function getMin(arr: Float32Array, stride: number): number[] {
  const min = new Array(stride).fill(Infinity);
  for (let i = 0; i < arr.length; i += stride) {
    for (let j = 0; j < stride; j++) {
      min[j] = Math.min(min[j], arr[i + j]);
    }
  }
  return min;
}

function getMax(arr: Float32Array, stride: number): number[] {
  const max = new Array(stride).fill(-Infinity);
  for (let i = 0; i < arr.length; i += stride) {
    for (let j = 0; j < stride; j++) {
      max[j] = Math.max(max[j], arr[i + j]);
    }
  }
  return max;
}

function generateMtlContent(materialName: string, textureFileName: string, material: MaterialProperties): string {
  const lines: string[] = [];
  lines.push("# MTL file generated by CreateMeshTool");
  lines.push("");
  lines.push(`newmtl ${materialName}`);

  const ambient = material.ambient || { r: 0.2, g: 0.2, b: 0.2 };
  lines.push(`Ka ${ambient.r} ${ambient.g} ${ambient.b}`);

  const diffuse = material.diffuse || { r: 1.0, g: 1.0, b: 1.0 };
  lines.push(`Kd ${diffuse.r} ${diffuse.g} ${diffuse.b}`);

  const specular = material.specular || { r: 0.5, g: 0.5, b: 0.5 };
  lines.push(`Ks ${specular.r} ${specular.g} ${specular.b}`);

  lines.push(`Ns ${material.shininess || 50}`);
  lines.push(`d ${material.opacity !== undefined ? material.opacity : 1.0}`);
  lines.push("illum 2");
  lines.push(`map_Kd ${textureFileName}`);

  return lines.join("\n") + "\n";
}

function parseObj(content: string): ParsedObj {
  const vertices: number[] = [];
  const normals: number[] = [];
  const texCoords: number[] = [];
  const faces: number[] = [];

  const tempVertices: number[][] = [];
  const tempNormals: number[][] = [];
  const tempTexCoords: number[][] = [];

  const lines = content.split("\n");
  for (const line of lines) {
    const parts = line.trim().split(/\s+/);
    const cmd = parts[0];

    switch (cmd) {
      case "v":
        tempVertices.push([
          parseFloat(parts[1]) || 0,
          parseFloat(parts[2]) || 0,
          parseFloat(parts[3]) || 0,
        ]);
        break;
      case "vn":
        tempNormals.push([
          parseFloat(parts[1]) || 0,
          parseFloat(parts[2]) || 0,
          parseFloat(parts[3]) || 0,
        ]);
        break;
      case "vt":
        tempTexCoords.push([
          parseFloat(parts[1]) || 0,
          parseFloat(parts[2]) || 0,
        ]);
        break;
      case "f": {
        const faceVerts: FaceVertex[] = [];
        for (let i = 1; i < parts.length; i++) {
          const indices = parts[i].split("/");
          const vi = parseInt(indices[0], 10) - 1;
          const ti = indices[1] ? parseInt(indices[1], 10) - 1 : -1;
          const ni = indices[2] ? parseInt(indices[2], 10) - 1 : -1;
          faceVerts.push({ vi, ti, ni });
        }

        // Triangulate if needed (fan triangulation)
        for (let i = 1; i < faceVerts.length - 1; i++) {
          const v0 = faceVerts[0];
          const v1 = faceVerts[i];
          const v2 = faceVerts[i + 1];

          for (const v of [v0, v1, v2]) {
            if (tempVertices[v.vi]) {
              vertices.push(...tempVertices[v.vi]);
            }
            if (v.ti >= 0 && tempTexCoords[v.ti]) {
              texCoords.push(...tempTexCoords[v.ti]);
            }
            if (v.ni >= 0 && tempNormals[v.ni]) {
              normals.push(...tempNormals[v.ni]);
            }
            faces.push(faces.length);
          }
        }
        break;
      }
    }
  }

  return {
    vertices: new Float32Array(vertices),
    normals: normals.length > 0 ? new Float32Array(normals) : null,
    texCoords: texCoords.length > 0 ? new Float32Array(texCoords) : null,
    faces: new Uint32Array(faces),
  };
}

function buildGltfDocument(
  vertices: Float32Array,
  normals: Float32Array | null,
  texCoords: Float32Array | null,
  faces: Uint32Array,
  textureBuffer: Buffer,
  mimeType: string,
  material: MaterialProperties,
  forGlb: boolean,
): GltfDocument {
  const gltf: GltfDocument = {
    asset: { version: "2.0", generator: "CreateMeshTool" },
    scene: 0,
    scenes: [{ nodes: [0] }],
    nodes: [{ mesh: 0 }],
    meshes: [{ primitives: [{ attributes: { POSITION: 0 }, indices: 1, material: 0 }] }],
    materials: [{
      pbrMetallicRoughness: {
        baseColorTexture: { index: 0 },
        metallicFactor: 0.0,
        roughnessFactor: 0.8,
      },
    }],
    textures: [{ source: 0, sampler: 0 }],
    samplers: [{ magFilter: 9729, minFilter: 9987, wrapS: 10497, wrapT: 10497 }],
    images: [],
    accessors: [],
    bufferViews: [],
    buffers: [],
  };

  // Apply additional material properties
  if (material.diffuse) {
    (gltf.materials[0] as any).pbrMetallicRoughness.baseColorFactor = [
      material.diffuse.r || 1,
      material.diffuse.g || 1,
      material.diffuse.b || 1,
      material.opacity || 1,
    ];
  }

  // Build binary buffer
  const buffers: Buffer[] = [];
  let byteOffset = 0;

  // Positions
  const positionBuffer = Buffer.from(vertices.buffer);
  buffers.push(positionBuffer);
  gltf.bufferViews.push({ buffer: 0, byteOffset, byteLength: positionBuffer.length, target: 34962 });
  gltf.accessors.push({
    bufferView: 0,
    byteOffset: 0,
    componentType: 5126,
    count: vertices.length / 3,
    type: "VEC3",
    min: getMin(vertices, 3),
    max: getMax(vertices, 3),
  });
  byteOffset += positionBuffer.length;

  // Indices
  const indexBuffer = Buffer.from(faces.buffer);
  buffers.push(indexBuffer);
  gltf.bufferViews.push({ buffer: 0, byteOffset, byteLength: indexBuffer.length, target: 34963 });
  gltf.accessors.push({
    bufferView: 1,
    byteOffset: 0,
    componentType: 5125,
    count: faces.length,
    type: "SCALAR",
  });
  byteOffset += indexBuffer.length;

  let attrIndex = 2;

  // Texture coordinates
  if (texCoords && texCoords.length > 0) {
    const texCoordBuffer = Buffer.from(texCoords.buffer);
    buffers.push(texCoordBuffer);
    gltf.bufferViews.push({ buffer: 0, byteOffset, byteLength: texCoordBuffer.length, target: 34962 });
    gltf.accessors.push({
      bufferView: attrIndex,
      byteOffset: 0,
      componentType: 5126,
      count: texCoords.length / 2,
      type: "VEC2",
    });
    gltf.meshes[0].primitives[0].attributes.TEXCOORD_0 = attrIndex;
    byteOffset += texCoordBuffer.length;
    attrIndex++;
  }

  // Normals
  if (normals && normals.length > 0) {
    const normalBuffer = Buffer.from(normals.buffer);
    buffers.push(normalBuffer);
    gltf.bufferViews.push({ buffer: 0, byteOffset, byteLength: normalBuffer.length, target: 34962 });
    gltf.accessors.push({
      bufferView: attrIndex,
      byteOffset: 0,
      componentType: 5126,
      count: normals.length / 3,
      type: "VEC3",
    });
    gltf.meshes[0].primitives[0].attributes.NORMAL = attrIndex;
    byteOffset += normalBuffer.length;
    attrIndex++;
  }

  // Image
  if (forGlb) {
    const padding = (4 - (byteOffset % 4)) % 4;
    if (padding > 0) {
      buffers.push(Buffer.alloc(padding));
      byteOffset += padding;
    }
    buffers.push(textureBuffer);
    gltf.bufferViews.push({ buffer: 0, byteOffset, byteLength: textureBuffer.length });
    gltf.images.push({ bufferView: gltf.bufferViews.length - 1, mimeType });
    byteOffset += textureBuffer.length;
  } else {
    gltf.images.push({ uri: `data:${mimeType};base64,${textureBuffer.toString("base64")}` });
  }

  // Combine all buffers
  const combinedBuffer = Buffer.concat(buffers);

  if (forGlb) {
    gltf.buffers.push({ byteLength: combinedBuffer.length });
    gltf._binaryBuffer = combinedBuffer;
  } else {
    gltf.buffers.push({
      uri: `data:application/octet-stream;base64,${combinedBuffer.toString("base64")}`,
      byteLength: combinedBuffer.length,
    });
  }

  return gltf;
}

function generateGlb(gltf: GltfDocument): Buffer {
  const binaryBuffer = gltf._binaryBuffer!;
  delete gltf._binaryBuffer;

  const jsonString = JSON.stringify(gltf);
  const jsonBuffer = Buffer.from(jsonString, "utf-8");

  const jsonPadding = (4 - (jsonBuffer.length % 4)) % 4;
  const paddedJsonBuffer = Buffer.concat([jsonBuffer, Buffer.alloc(jsonPadding, 0x20)]);

  const binPadding = (4 - (binaryBuffer.length % 4)) % 4;
  const paddedBinBuffer = Buffer.concat([binaryBuffer, Buffer.alloc(binPadding, 0x00)]);

  const header = Buffer.alloc(12);
  header.writeUInt32LE(0x46546c67, 0); // Magic: glTF
  header.writeUInt32LE(2, 4);          // Version: 2
  header.writeUInt32LE(12 + 8 + paddedJsonBuffer.length + 8 + paddedBinBuffer.length, 8);

  const jsonChunkHeader = Buffer.alloc(8);
  jsonChunkHeader.writeUInt32LE(paddedJsonBuffer.length, 0);
  jsonChunkHeader.writeUInt32LE(0x4e4f534a, 4); // Type: JSON

  const binChunkHeader = Buffer.alloc(8);
  binChunkHeader.writeUInt32LE(paddedBinBuffer.length, 0);
  binChunkHeader.writeUInt32LE(0x004e4942, 4); // Type: BIN

  return Buffer.concat([header, jsonChunkHeader, paddedJsonBuffer, binChunkHeader, paddedBinBuffer]);
}

// ── OBJ Mesh Creation ───────────────────────────────────────

async function createObjMesh(
  ctx: ToolContext,
  sessionId: string | undefined,
  absObjPath: string,
  absTexturePath: string,
  outputPath: string,
  options: MeshOptions,
  material: MaterialProperties,
): Promise<Record<string, unknown>> {
  const materialName = options.materialName || "textured_material";

  let outputDir: string;
  let objFileName: string;
  if (outputPath.endsWith(".obj")) {
    outputDir = dirname(outputPath);
    objFileName = basename(outputPath);
  } else {
    outputDir = outputPath;
    objFileName = basename(absObjPath);
  }

  const absOutputDir = await ctx.sandbox.resolvePath(sessionId, outputDir);

  if (options.createDirectories !== false) {
    await ctx.sandbox.ensureParentDir(join(absOutputDir, "placeholder"));
  }

  const mtlFileName = objFileName.replace(".obj", ".mtl");
  const textureFileName = basename(absTexturePath);

  const absOutputObjPath = join(absOutputDir, objFileName);
  const absOutputMtlPath = join(absOutputDir, mtlFileName);
  const absOutputTexturePath = join(absOutputDir, textureFileName);

  if (!options.overwrite) {
    if (existsSync(absOutputObjPath)) {
      throw new Error(`Output OBJ file already exists: ${join(outputDir, objFileName)}`);
    }
    if (existsSync(absOutputMtlPath)) {
      throw new Error(`Output MTL file already exists: ${join(outputDir, mtlFileName)}`);
    }
  }

  // Read and modify OBJ file
  let objContent = await readFile(absObjPath, "utf-8");
  objContent = objContent.replace(/^mtllib\s+.*$/gm, "");
  objContent = objContent.replace(/^usemtl\s+.*$/gm, "");

  const lines = objContent.split("\n");
  let insertIndex = 0;
  for (let i = 0; i < lines.length; i++) {
    if (!lines[i].startsWith("#") && lines[i].trim() !== "") {
      insertIndex = i;
      break;
    }
    insertIndex = i + 1;
  }
  lines.splice(insertIndex, 0, `mtllib ${mtlFileName}`, "");

  let usemtlAdded = false;
  for (let i = 0; i < lines.length; i++) {
    if (lines[i].trim().startsWith("f ") && !usemtlAdded) {
      lines.splice(i, 0, `usemtl ${materialName}`);
      usemtlAdded = true;
      break;
    }
  }

  objContent = lines.join("\n");

  const mtlContent = generateMtlContent(materialName, textureFileName, material);

  const objBuffer = Buffer.from(objContent, "utf-8");
  const mtlBuffer = Buffer.from(mtlContent, "utf-8");

  const textureStats = await stat(absTexturePath);
  const totalSize = objBuffer.length + mtlBuffer.length + textureStats.size;
  if (totalSize > MAX_FILE_SIZE) {
    throw new Error(`Total mesh size ${totalSize} bytes exceeds maximum ${MAX_FILE_SIZE} bytes`);
  }

  await writeFile(absOutputObjPath, objBuffer);
  ctx.sandbox.updateSandboxSize(sessionId, objBuffer.length);

  await writeFile(absOutputMtlPath, mtlBuffer);
  ctx.sandbox.updateSandboxSize(sessionId, mtlBuffer.length);

  if (options.copySourceFiles !== false && absOutputTexturePath !== absTexturePath) {
    await copyFile(absTexturePath, absOutputTexturePath);
    ctx.sandbox.updateSandboxSize(sessionId, textureStats.size);
  }

  const objStats = await stat(absOutputObjPath);
  const mtlStats = await stat(absOutputMtlPath);

  return {
    success: true,
    format: "obj",
    files: {
      obj: {
        path: join(outputDir, objFileName),
        size: objStats.size,
        checksum: `sha256:${calculateChecksum(objBuffer)}`,
      },
      mtl: {
        path: join(outputDir, mtlFileName),
        size: mtlStats.size,
        checksum: `sha256:${calculateChecksum(mtlBuffer)}`,
      },
      texture: {
        path: join(outputDir, textureFileName),
        size: textureStats.size,
      },
    },
    materialName,
    created: new Date().toISOString(),
  };
}

// ── GLTF/GLB Mesh Creation ──────────────────────────────────

async function createGltfMesh(
  ctx: ToolContext,
  sessionId: string | undefined,
  absObjPath: string,
  absTexturePath: string,
  outputPath: string,
  format: "glb" | "gltf",
  options: MeshOptions,
  material: MaterialProperties,
): Promise<Record<string, unknown>> {
  const objContent = await readFile(absObjPath, "utf-8");
  const { vertices, normals, texCoords, faces } = parseObj(objContent);

  const textureBuffer = await readFile(absTexturePath);
  const textureExt = extname(absTexturePath).slice(1).toLowerCase();
  const mimeType = getMimeType(textureExt);

  const gltf = buildGltfDocument(vertices, normals, texCoords, faces, textureBuffer, mimeType, material, format === "glb");

  let absOutputPath: string;
  if (outputPath.endsWith(`.${format}`)) {
    absOutputPath = await ctx.sandbox.resolvePath(sessionId, outputPath);
  } else {
    const fileName = basename(absObjPath, ".obj") + `.${format}`;
    absOutputPath = await ctx.sandbox.resolvePath(sessionId, join(outputPath, fileName));
  }

  if (options.createDirectories !== false) {
    await ctx.sandbox.ensureParentDir(absOutputPath);
  }

  if (!options.overwrite && existsSync(absOutputPath)) {
    throw new Error(`Output file already exists: ${outputPath}`);
  }

  let outputBuffer: Buffer;
  if (format === "glb") {
    outputBuffer = generateGlb(gltf);
  } else {
    outputBuffer = Buffer.from(JSON.stringify(gltf, null, 2), "utf-8");
  }

  if (outputBuffer.length > MAX_FILE_SIZE) {
    throw new Error(`Output size ${outputBuffer.length} bytes exceeds maximum ${MAX_FILE_SIZE} bytes`);
  }

  await writeFile(absOutputPath, outputBuffer);
  ctx.sandbox.updateSandboxSize(sessionId, outputBuffer.length);

  const stats = await stat(absOutputPath);

  return {
    success: true,
    format,
    path: outputPath.endsWith(`.${format}`) ? outputPath : join(outputPath, basename(absOutputPath)),
    size: stats.size,
    checksum: `sha256:${calculateChecksum(outputBuffer)}`,
    vertexCount: vertices.length / 3,
    faceCount: faces.length / 3,
    created: new Date().toISOString(),
  };
}

// ── Execute ─────────────────────────────────────────────────

async function execute(args: Record<string, unknown>, ctx: ToolContext): Promise<ToolResult> {
  const sessionId = args.sessionId as string | undefined;
  const objPath = args.objPath as string | undefined;
  const texturePath = args.texturePath as string | undefined;
  const outputPath = args.outputPath as string | undefined;
  const options = (args.options as MeshOptions) ?? {};
  const material = (args.material as MaterialProperties) ?? {};

  if (!objPath) return formatError("objPath is required");
  if (!texturePath) return formatError("texturePath is required");
  if (!outputPath) return formatError("outputPath is required");

  const absObjPath = await ctx.sandbox.resolvePath(sessionId, objPath);
  const absTexturePath = await ctx.sandbox.resolvePath(sessionId, texturePath);

  if (!existsSync(absObjPath)) return formatError(`OBJ file not found: ${objPath}`);
  if (!existsSync(absTexturePath)) return formatError(`Texture file not found: ${texturePath}`);

  const textureExt = extname(texturePath).slice(1).toLowerCase();
  if (!SUPPORTED_TEXTURE_FORMATS.includes(textureExt)) {
    return formatError(`Unsupported texture format: ${textureExt}. Supported: ${SUPPORTED_TEXTURE_FORMATS.join(", ")}`);
  }

  const outputFormat = options.outputFormat || "obj";
  if (!SUPPORTED_OUTPUT_FORMATS.includes(outputFormat)) {
    return formatError(`Unsupported output format: ${outputFormat}. Supported: ${SUPPORTED_OUTPUT_FORMATS.join(", ")}`);
  }

  try {
    let result: Record<string, unknown>;
    switch (outputFormat) {
      case "obj":
        result = await createObjMesh(ctx, sessionId, absObjPath, absTexturePath, outputPath, options, material);
        break;
      case "glb":
      case "gltf":
        result = await createGltfMesh(ctx, sessionId, absObjPath, absTexturePath, outputPath, outputFormat, options, material);
        break;
      default:
        return formatError(`Output format not implemented: ${outputFormat}`);
    }
    return formatResponse(result);
  } catch (err: any) {
    return formatError(`Failed to create mesh: ${err.message}`);
  }
}

// ── Tool Definition ─────────────────────────────────────────

const createMeshTool: Tool = {
  name: "create_mesh",
  description:
    "Create a complete 3D mesh by combining an OBJ file with a texture image. Generates properly linked OBJ+MTL files or converts to GLB/GLTF format. The mesh can then be used in 3D applications, game engines, or web viewers.",
  needsSandbox: true,
  inputSchema: {
    type: "object",
    properties: {
      sessionId: {
        type: "string",
        description: "Session ID for sandbox isolation (optional, uses \"default\" if not provided)",
      },
      objPath: {
        type: "string",
        description: "Path to the source OBJ file within the sandbox",
      },
      texturePath: {
        type: "string",
        description: "Path to the texture image file within the sandbox (PNG, JPG, TGA, BMP, TIFF, WebP)",
      },
      outputPath: {
        type: "string",
        description: "Output path (directory for OBJ format, or full file path for GLB/GLTF)",
      },
      options: {
        type: "object",
        description: "Mesh creation options",
        properties: {
          overwrite: { type: "boolean", default: false, description: "Overwrite if output files already exist" },
          createDirectories: { type: "boolean", default: true, description: "Create parent directories if needed" },
          materialName: { type: "string", default: "textured_material", description: "Name for the material in MTL file" },
          copySourceFiles: { type: "boolean", default: true, description: "Copy source OBJ and texture to output directory (OBJ format only)" },
          outputFormat: { type: "string", enum: ["obj", "glb", "gltf"], default: "obj", description: "Output format: obj (OBJ+MTL), glb (binary GLTF), gltf (JSON GLTF)" },
        },
      },
      material: {
        type: "object",
        description: "Additional material properties",
        properties: {
          ambient: {
            type: "object",
            description: "Ambient color",
            properties: {
              r: { type: "number", minimum: 0, maximum: 1 },
              g: { type: "number", minimum: 0, maximum: 1 },
              b: { type: "number", minimum: 0, maximum: 1 },
            },
          },
          diffuse: {
            type: "object",
            description: "Diffuse/base color",
            properties: {
              r: { type: "number", minimum: 0, maximum: 1 },
              g: { type: "number", minimum: 0, maximum: 1 },
              b: { type: "number", minimum: 0, maximum: 1 },
            },
          },
          specular: {
            type: "object",
            description: "Specular highlight color",
            properties: {
              r: { type: "number", minimum: 0, maximum: 1 },
              g: { type: "number", minimum: 0, maximum: 1 },
              b: { type: "number", minimum: 0, maximum: 1 },
            },
          },
          shininess: { type: "number", minimum: 0, maximum: 1000, default: 50, description: "Specular exponent (shininess)" },
          opacity: { type: "number", minimum: 0, maximum: 1, default: 1, description: "Material opacity (1 = fully opaque)" },
        },
      },
    },
    required: ["objPath", "texturePath", "outputPath"],
  },
  execute,
};

export default createMeshTool;
