import { writeFile, stat } from "fs/promises";
import { existsSync } from "fs";
import { createHash } from "crypto";
import { extname, basename, dirname, join } from "path";
import type { Tool, ToolResult, ToolContext } from "./types";
import { formatResponse, formatError } from "./types";

// -- Types --------------------------------------------------------------------

interface Vertex {
  x: number;
  y: number;
  z: number;
}

interface TextureCoord {
  u: number;
  v: number;
}

interface Normal {
  x: number;
  y: number;
  z: number;
}

interface Face {
  vertices: number[];
  textures?: (number | null)[];
  normals?: (number | null)[];
}

interface ColorRGB {
  r?: number;
  g?: number;
  b?: number;
}

interface Material {
  ambient?: ColorRGB;
  diffuse?: ColorRGB;
  specular?: ColorRGB;
  shininess?: number;
  opacity?: number;
  illumination?: number;
  diffuseMap?: string;
  normalMap?: string;
  specularMap?: string;
}

interface ObjOptions {
  overwrite?: boolean;
  createDirectories?: boolean;
  objectName?: string;
  groupName?: string;
  materialLibrary?: string;
  materialName?: string;
  generateMtl?: boolean;
  material?: Material;
}

interface ObjContentData {
  vertices: Vertex[];
  textureCoords: TextureCoord[];
  normals: Normal[];
  faces: Face[];
  options: ObjOptions;
}

// -- Helpers ------------------------------------------------------------------

function calculateChecksum(buffer: Buffer): string {
  return createHash("sha256").update(buffer).digest("hex");
}

function generateObjContent(data: ObjContentData): string {
  const { vertices, textureCoords, normals, faces, options } = data;
  const lines: string[] = [];

  // Header comment
  lines.push("# OBJ file generated by CreateObjTool");
  lines.push(`# Vertices: ${vertices.length}, Faces: ${faces.length}`);
  lines.push("");

  // Material library reference
  if (options.materialLibrary) {
    lines.push(`mtllib ${options.materialLibrary}`);
    lines.push("");
  }

  // Object name
  if (options.objectName) {
    lines.push(`o ${options.objectName}`);
  }

  // Group name
  if (options.groupName) {
    lines.push(`g ${options.groupName}`);
  }

  // Vertices (v x y z)
  for (const v of vertices) {
    if (typeof v.x !== "number" || typeof v.y !== "number" || typeof v.z !== "number") {
      throw new Error("Each vertex must have numeric x, y, z properties");
    }
    lines.push(`v ${v.x} ${v.y} ${v.z}`);
  }
  if (vertices.length > 0) lines.push("");

  // Texture coordinates (vt u v)
  for (const vt of textureCoords) {
    if (typeof vt.u !== "number" || typeof vt.v !== "number") {
      throw new Error("Each texture coordinate must have numeric u, v properties");
    }
    lines.push(`vt ${vt.u} ${vt.v}`);
  }
  if (textureCoords.length > 0) lines.push("");

  // Normals (vn x y z)
  for (const vn of normals) {
    if (typeof vn.x !== "number" || typeof vn.y !== "number" || typeof vn.z !== "number") {
      throw new Error("Each normal must have numeric x, y, z properties");
    }
    lines.push(`vn ${vn.x} ${vn.y} ${vn.z}`);
  }
  if (normals.length > 0) lines.push("");

  // Material usage
  if (options.materialName) {
    lines.push(`usemtl ${options.materialName}`);
  }

  // Faces (f v1/vt1/vn1 v2/vt2/vn2 ...)
  for (const face of faces) {
    if (!Array.isArray(face.vertices) || face.vertices.length < 3) {
      throw new Error("Each face must have at least 3 vertex indices");
    }

    const faceIndices = face.vertices.map((vi, idx) => {
      if (typeof vi !== "number" || vi < 1 || vi > vertices.length) {
        throw new Error(`Invalid vertex index ${vi}. Must be 1-${vertices.length}`);
      }

      let indexStr = vi.toString();

      if (face.textures && face.textures[idx] !== undefined) {
        const ti = face.textures[idx];
        if (ti !== null && (ti! < 1 || ti! > textureCoords.length)) {
          throw new Error(`Invalid texture index ${ti}. Must be 1-${textureCoords.length}`);
        }
        indexStr += "/" + (ti || "");

        if (face.normals && face.normals[idx] !== undefined) {
          const ni = face.normals[idx];
          if (ni !== null && (ni! < 1 || ni! > normals.length)) {
            throw new Error(`Invalid normal index ${ni}. Must be 1-${normals.length}`);
          }
          indexStr += "/" + (ni || "");
        }
      } else if (face.normals && face.normals[idx] !== undefined) {
        // Normal without texture: v//vn format
        const ni = face.normals[idx];
        if (ni !== null && (ni! < 1 || ni! > normals.length)) {
          throw new Error(`Invalid normal index ${ni}. Must be 1-${normals.length}`);
        }
        indexStr += "//" + (ni || "");
      }

      return indexStr;
    });

    lines.push(`f ${faceIndices.join(" ")}`);
  }

  return lines.join("\n") + "\n";
}

async function generateMtlFile(
  ctx: ToolContext,
  sessionId: string | undefined,
  objPath: string,
  material: Material,
  options: ObjOptions
): Promise<string> {
  const mtlName = basename(objPath, ".obj") + ".mtl";
  const mtlPath = join(dirname(objPath), mtlName);
  const absMtlPath = await ctx.sandbox.resolvePath(sessionId, mtlPath);

  const lines: string[] = [];
  lines.push("# MTL file generated by CreateObjTool");
  lines.push("");
  lines.push(`newmtl ${options.materialName || "default_material"}`);

  // Ambient color (Ka)
  if (material.ambient) {
    const { r = 0.2, g = 0.2, b = 0.2 } = material.ambient;
    lines.push(`Ka ${r} ${g} ${b}`);
  }

  // Diffuse color (Kd)
  if (material.diffuse) {
    const { r = 0.8, g = 0.8, b = 0.8 } = material.diffuse;
    lines.push(`Kd ${r} ${g} ${b}`);
  }

  // Specular color (Ks)
  if (material.specular) {
    const { r = 1.0, g = 1.0, b = 1.0 } = material.specular;
    lines.push(`Ks ${r} ${g} ${b}`);
  }

  // Specular exponent (Ns)
  if (material.shininess !== undefined) {
    lines.push(`Ns ${material.shininess}`);
  }

  // Transparency (d)
  if (material.opacity !== undefined) {
    lines.push(`d ${material.opacity}`);
  }

  // Illumination model (illum)
  if (material.illumination !== undefined) {
    lines.push(`illum ${material.illumination}`);
  }

  // Texture maps
  if (material.diffuseMap) lines.push(`map_Kd ${material.diffuseMap}`);
  if (material.normalMap) lines.push(`bump ${material.normalMap}`);
  if (material.specularMap) lines.push(`map_Ks ${material.specularMap}`);

  const mtlContent = lines.join("\n") + "\n";
  const mtlBuffer = Buffer.from(mtlContent, "utf-8");

  await ctx.sandbox.ensureParentDir(absMtlPath);
  await writeFile(absMtlPath, mtlBuffer);
  ctx.sandbox.updateSandboxSize(sessionId, mtlBuffer.length);

  return mtlPath;
}

// -- Execute ------------------------------------------------------------------

async function execute(args: Record<string, unknown>, ctx: ToolContext): Promise<ToolResult> {
  const sessionId = args.sessionId as string | undefined;
  const path = args.path as string | undefined;
  const inputType = (args.inputType as string) ?? "structured";
  const vertices = (args.vertices as Vertex[]) ?? [];
  const textureCoords = (args.textureCoords as TextureCoord[]) ?? [];
  const normals = (args.normals as Normal[]) ?? [];
  const faces = (args.faces as Face[]) ?? [];
  const rawContent = args.rawContent as string | undefined;
  const options = (args.options as ObjOptions) ?? {};

  const maxFileSize = (ctx.config.maxObjFileSize as number) ?? 100 * 1024 * 1024;

  if (!path) return formatError("path is required");

  // Validate file extension
  const ext = extname(path).toLowerCase();
  if (ext && ext !== ".obj") {
    return formatError(`Invalid file extension: ${ext}. OBJ files must have .obj extension.`);
  }

  // Resolve path within sandbox
  const absPath = await ctx.sandbox.resolvePath(sessionId, path);

  // Check if file exists
  const fileExists = existsSync(absPath);
  if (fileExists && !options.overwrite) {
    return formatError(`File already exists: ${path}. Set options.overwrite=true to replace.`);
  }

  // Generate OBJ content
  let objContent: string;
  try {
    if (inputType === "raw") {
      if (!rawContent) {
        return formatError('rawContent is required for inputType "raw"');
      }
      objContent = rawContent;
    } else {
      objContent = generateObjContent({
        vertices,
        textureCoords,
        normals,
        faces,
        options,
      });
    }
  } catch (err: any) {
    return formatError(`Failed to generate OBJ content: ${err.message}`);
  }

  const buffer = Buffer.from(objContent, "utf-8");

  // Validate size
  if (buffer.length > maxFileSize) {
    return formatError(
      `OBJ file size ${buffer.length} bytes exceeds maximum ${maxFileSize} bytes`
    );
  }

  try {
    ctx.sandbox.validateFileSize(buffer.length, sessionId);
  } catch (err: any) {
    return formatError(`Sandbox size limit exceeded: ${err.message}`);
  }

  // Ensure parent directory exists
  if (options.createDirectories !== false) {
    await ctx.sandbox.ensureParentDir(absPath);
  }

  // Write the OBJ file
  await writeFile(absPath, buffer);

  // Update size tracking
  const existingSize = fileExists
    ? (await stat(absPath).catch(() => ({ size: 0 }))).size
    : 0;
  ctx.sandbox.updateSandboxSize(sessionId, buffer.length - existingSize);

  // Generate MTL file if requested
  let mtlPath: string | null = null;
  if (options.generateMtl && options.material) {
    mtlPath = await generateMtlFile(ctx, sessionId, path, options.material, options);
  }

  // Calculate checksum
  const checksum = calculateChecksum(buffer);
  const stats = await stat(absPath);

  const response: Record<string, unknown> = {
    success: true,
    path,
    size: stats.size,
    checksum: `sha256:${checksum}`,
    created: stats.birthtime.toISOString(),
    vertexCount: vertices.length,
    faceCount: faces.length,
    textureCoordCount: textureCoords.length,
    normalCount: normals.length,
  };

  if (mtlPath) {
    response.mtlPath = mtlPath;
  }

  return formatResponse(response);
}

// -- Tool Definition ----------------------------------------------------------

const createObjTool: Tool = {
  name: "create_obj",
  description:
    "Create a Wavefront OBJ file for 3D models. Accepts structured data (vertices, faces, normals, texture coordinates) or raw OBJ content. Can optionally generate an accompanying MTL material file.",
  needsSandbox: true,
  inputSchema: {
    type: "object",
    properties: {
      sessionId: {
        type: "string",
        description:
          'Session ID for sandbox isolation (optional, uses "default" if not provided)',
      },
      path: {
        type: "string",
        description:
          'Output path for the OBJ file within the sandbox (e.g., "models/cube.obj")',
      },
      inputType: {
        type: "string",
        enum: ["structured", "raw"],
        default: "structured",
        description:
          'Input type: "structured" for vertex/face arrays, "raw" for raw OBJ content',
      },
      vertices: {
        type: "array",
        items: {
          type: "object",
          properties: {
            x: { type: "number" },
            y: { type: "number" },
            z: { type: "number" },
          },
          required: ["x", "y", "z"],
        },
        description: "Array of vertex positions (for structured input)",
      },
      textureCoords: {
        type: "array",
        items: {
          type: "object",
          properties: {
            u: { type: "number", minimum: 0, maximum: 1 },
            v: { type: "number", minimum: 0, maximum: 1 },
          },
          required: ["u", "v"],
        },
        description: "Array of texture coordinates (UV mapping, for structured input)",
      },
      normals: {
        type: "array",
        items: {
          type: "object",
          properties: {
            x: { type: "number" },
            y: { type: "number" },
            z: { type: "number" },
          },
          required: ["x", "y", "z"],
        },
        description: "Array of vertex normals (for structured input)",
      },
      faces: {
        type: "array",
        items: {
          type: "object",
          properties: {
            vertices: {
              type: "array",
              items: { type: "integer", minimum: 1 },
              minItems: 3,
              description: "Vertex indices (1-based)",
            },
            textures: {
              type: "array",
              items: { type: "integer", minimum: 1 },
              description: "Texture coordinate indices (1-based, optional)",
            },
            normals: {
              type: "array",
              items: { type: "integer", minimum: 1 },
              description: "Normal indices (1-based, optional)",
            },
          },
          required: ["vertices"],
        },
        description: "Array of face definitions (for structured input)",
      },
      rawContent: {
        type: "string",
        description: "Raw OBJ file content (for raw input type)",
      },
      options: {
        type: "object",
        description: "OBJ creation options",
        properties: {
          overwrite: {
            type: "boolean",
            default: false,
            description: "Overwrite if file already exists",
          },
          createDirectories: {
            type: "boolean",
            default: true,
            description: "Create parent directories if needed",
          },
          objectName: {
            type: "string",
            description: 'Name for the object (OBJ "o" directive)',
          },
          groupName: {
            type: "string",
            description: 'Name for the group (OBJ "g" directive)',
          },
          materialLibrary: {
            type: "string",
            description: 'MTL file to reference (OBJ "mtllib" directive)',
          },
          materialName: {
            type: "string",
            description: 'Material name to use (OBJ "usemtl" directive)',
          },
          generateMtl: {
            type: "boolean",
            default: false,
            description: "Generate an accompanying MTL material file",
          },
          material: {
            type: "object",
            description: "Material properties for MTL generation",
            properties: {
              ambient: {
                type: "object",
                properties: {
                  r: { type: "number", minimum: 0, maximum: 1 },
                  g: { type: "number", minimum: 0, maximum: 1 },
                  b: { type: "number", minimum: 0, maximum: 1 },
                },
              },
              diffuse: {
                type: "object",
                properties: {
                  r: { type: "number", minimum: 0, maximum: 1 },
                  g: { type: "number", minimum: 0, maximum: 1 },
                  b: { type: "number", minimum: 0, maximum: 1 },
                },
              },
              specular: {
                type: "object",
                properties: {
                  r: { type: "number", minimum: 0, maximum: 1 },
                  g: { type: "number", minimum: 0, maximum: 1 },
                  b: { type: "number", minimum: 0, maximum: 1 },
                },
              },
              shininess: { type: "number", minimum: 0, maximum: 1000 },
              opacity: { type: "number", minimum: 0, maximum: 1 },
              illumination: { type: "integer", minimum: 0, maximum: 10 },
              diffuseMap: { type: "string", description: "Path to diffuse texture map" },
              normalMap: { type: "string", description: "Path to normal/bump map" },
              specularMap: { type: "string", description: "Path to specular map" },
            },
          },
        },
      },
    },
    required: ["path"],
  },
  execute,
};

export default createObjTool;
